### ISSUE TITLE
Issue on page /chapter1/fundamentals_code.html

### ISSUE THREAD

**Issue by MonteiroI** [jorgensd/dolfinx-tutorial#76]
Hi. When I was try to run the command

`mpirun -n 2 python3 t1.py`

I received the message

AttributeError: module 'dolfinx.mesh' has no attribute 'create_unit_square'

I didn't find the create_unit_square function in the module dolfinx.

**Comment by jorgensd** [comment]
What version of dolfinx are you running?
Could you tell me the output of `print(dolfinx.__version__)`
`print(dolfinx.common.git_commit_hash)`

**Comment by MonteiroI** [comment]
Hi, I am a user fenics legacy version since 2017. Today I started to use the fenicsx version. I followed the intructions to install fenicsx on a ubuntu system by add the ppa. Using the command
`print(f"DOLFINx version: {dolfinx.__version__} based on GIT commit: {dolfinx.git_commit_hash} of https://github.com/FEniCS/dolfinx/")`
I received the message
DOLFINx version: 0.3.0 based on GIT commit: unknown of https://github.com/FEniCS/dolfinx/

**Comment by jorgensd** [comment]
To run a tutorial compatible with 0.3.0, you need to use the notebooks from the 0.3.0 release https://github.com/jorgensd/dolfinx-tutorial/tree/v0.3.0

**Comment by jorgensd** [comment]
> I would like to work with the 0.4.0 version. Is possible to install the 0.4.0 version using ppa in a ubuntu system?

It is not on the PPA yet, as the release is fairly recent (last week).

**Comment by MonteiroI** [comment]
Ok. Thank you. Best regards

**Comment by MonteiroI** [comment]
I'm sorry. I'm totally lost. How can I see the tutorial in the 0.3.0 version? Could you give me a direction? I opened  https://github.com/jorgensd/dolfinx-tutorial/tree/v0.3.0 but I don't know how to see this tutorial version. When I click on the webpage in the readme.md I entered in 0.4.0 tutorial version.

**Comment by jorgensd** [comment]
There is no webpage version of 0.3.0, But you can download the notebooks from the link I supplied (They are inside chapter1, chapter2 etc).

**Comment by MonteiroI** [comment]
Ok. I hadn't understood. Thank you.
